disp(' ')
%%
pause(0.5)
disp('                                                         ')
pause(0.5)
disp('Now you are safe in the Palace but the remedy still needs to be made. ')
pause(1.5)
disp('There is one missing ingredient in the vaccine,   ')
pause(1.5)
disp('and someone needs to email the supplier the co-ordinates.   ')
pause(1.5)
disp(' ')
pause(0.5)
disp('Do you?')
pause(1.0)
disp('   ')
pause(0.5)
disp('   ')
pause(0.5)
disp('1. Fight your way past Prince Charles''s troops and release the Queen,  ')
pause(0.5)
disp('in the hope that she''ll let you stay. ')
pause(0.5)
disp(' ')
pause(0.5)
disp('2. Leave it to someone else you just want to watch a bit of Netflix on the sofa.   ')
pause(0.5)
disp(' ')
pause(0.5)
L = input('Choose by typing 1 or 2    ');
pause(0.5)
disp(' ')
if L == 1;
    pause(0.5)
    disp('You send the email, and copy yourself in it just incase')
    pause(1.5)
    disp('The supplier makes the drop successfully, and the cure is developed.')
    pause(1.5)
    disp('It is distributed, and people are immunized.')
    pause(1.5)
    disp('It''s too late for those already bitten, but most of the population survives.')
    pause(1.5)
    disp(' ')
    pause(0.5)
    %%ADD EMAIL HERE%%
    winning
    
elseif L == 2;
     pause(0.5)
     disp('The Queen regrets her decision to let you stay, and exiles you outside the Palace. ')
     pause(1.5)
     disp('Someone else sends the email, the cure is developed, and people are immunized. ')
     pause(1.5)
     disp('Unfortunately it came too late for you, as you were eaten as soon as you were')
     pause(1.5)
     disp('thrown back over the wall by a swarm of zombies.')
     pause(1.5)
     disp(' ')
     pause(0.5)
     death
end